gsu/news/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import index,zap_consult,tvor,volon_naprav,trud_naprav,sec,deletepost,detail_v,otpisv, otpisgv,zapisgv,create,create_v,zapisv, zapis,zapisg,otpis,otpisg,cult,consult,otz, mass,sport,trud, POSTLoginView, profile, POSTLogoutView, ChangeUserInfoView, POSTChangeView, RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, detail

app_name = 'news'

urlpatterns = [
    path('', index, name='index'),
    path('<int:pk>/', detail, name='detail'),
    path('v/<int:pk>/', detail_v, name='detail_v'),
    path('cult/', cult, name='cult'),
    path('mass/', mass, name='mass'),
    path('sport/', sport, name='sport'),
    path('trud/', trud, name='trud'),
    path('consult/', consult, name='consult'),
    path('otz/', otz, name='otz'),
    path('sec/<int:pk>/', sec, name='sec'),
    path('tvor/<int:pk>/', tvor, name='tvor'),
    path('volon_naprav/<int:pk>/', volon_naprav, name='volon_naprav'),
    path('trud_naprav/<int:pk>/', trud_naprav, name='trud_naprav'),
    path('zapis_consult/<int:pk>/', zap_consult, name='zap_consult'),
    path('zapis/<int:pk>/', zapis, name='zapis'),
    path('zapisv/<int:pk1>/<int:pk2>', zapisv, name='zapisv'),
    path('zapisg/<int:pk>/', zapisg, name='zapisg'),
    path('zapisgv/<int:pk1>/<int:pk2>', zapisgv, name='zapisgv'),
    path('otpis/<int:pk>/', otpis, name='otpis'),
    path('otpisv/<int:pk1>/<int:pk2>', otpisv, name='otpisv'),
    path('otpisg/<int:pk>/', otpisg, name='otpisg'),
    path('otpisgv/<int:pk1>/<int:pk2>', otpisgv, name='otpisgv'),
    path('add/', create, name='add'),
    path('add_v/', create_v, name='add_v'),
    path('register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('register/done', RegisterDoneView.as_view(), name='register_done'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', POSTLoginView.as_view(), name='login'),
    path('logout/', POSTLogoutView.as_view(), name='logout'),
    path('profile/delete', DeleteUserView.as_view(), name='profile_delete'),
    path('profile/', profile, name='profile'),
    path('profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
    path('profile/password/change', POSTChangeView.as_view(), name='password_change'),  
    path('profile/deletepost/<int:pk>/', deletepost, name='delete_post'), 
]

gsu/postgram/urls.py
from django.contrib import admin
from django.conf import settings 
from django.urls import path, include 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls',namespace='')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gsu/news/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from .utilities import send_activation_notification
import os
from django.core.validators import MaxValueValidator , MinValueValidator


class AdvUser(AbstractUser):
    fac = (
        ('bio','Биологический факультет'),
        ('geo','Геолого-географический факультет'),
        ('ist','Факультет истории и межкультурных коммуникаций'),
        ('in','Факультет иностранных языков'),
        ('mat','Факультет математитики и ТП'),
        ('psi','Факультет психологии и педагогики'),
        ('fiz','Факультет физики и ИТ'),
        ('ffk','Факультет физической культуры'),
        ('fil','Филологический факультет'),
        ('eko','Экономический факультет'),
        ('yr','Юридичесий факультет'),
        )
        

    is_activated = models.BooleanField(default=True, db_index=True,verbose_name='Прошел активацию')
    avatar = models.ImageField(null=True, blank=True, upload_to="image/profile/",verbose_name='Аватарка')
    phone_num = models.CharField(unique = True, null = True, blank = False, max_length=13,verbose_name='Номер телефона')
    faculty = models.CharField(null = True, blank =False,choices=fac,max_length=50,verbose_name='Факультет')
    group = models.CharField(null = True, blank = False,max_length=10,verbose_name='Группа')



    class Meta(AbstractUser.Meta):
        pass

class Consult(models.Model):
    date = (
         ('9:00','9:00'),
         ('10:00','10:00'),
         ('11:00','11:00'),
         ('12:00','12:00'),
         ('13:00','13:00'),
         ('14:00','14:00'),
         ('15:00','15:00'),
        )
    eventdate = models.DateField(db_index=True,null=True,blank=False,verbose_name='Дата')
    eventtime = models.CharField(choices=date,blank=False,max_length=10,verbose_name='Время')
    zan = models.BooleanField(default=False, db_index=True,verbose_name='Занятость')

    class Meta:
        verbose_name_plural = 'Консультации'
        verbose_name = 'Консультация'
        ordering = ['eventdate']

class Post(models.Model):
    tag = (
        ('cult','Культурно-досуговая деятельность'),
        ('sport','Спортивная деятельность'),
        ('mass','Массовые мероприятия и выставки'),
        ('trud','Трудовая и волонтерская деятельность'),
        )

    name = models.CharField(null=True, blank=False,max_length=100,verbose_name='Заголовок')
    content = models.TextField(null=True, blank=False,verbose_name='Контент')
    image = models.ImageField(upload_to='image/%Y/%m/%d/', blank=True, null=True,verbose_name='Изображение')
    file = models.FileField(upload_to='files/%Y/%m/%d/', blank=True, null=True,verbose_name='Приклепленные файлы')
    video = models.FileField(upload_to='video/%Y/%m/%d/', blank=True, null=True,verbose_name='Видео')
    audio = models.FileField(upload_to='audio/%Y/%m/%d/', blank=True, null=True,verbose_name='Аудио')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, null=True,verbose_name='Автор')
    pubdate = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')
    eventtime = models.TimeField(db_index=True,null=True,blank=False,verbose_name='Время')
    eventdate = models.DateField(db_index=True,null=True,blank=False,verbose_name='Дата')
    stoim = models.CharField(null = True, blank = False, max_length=10,verbose_name='Стоимость')
    mesta = models.IntegerField(null = True, blank = False,default=2,validators=[MinValueValidator(0)],verbose_name='Количество мест всего') 
    mesta_now = models.IntegerField(null = True, blank = False,verbose_name='Количество мест сейчас')
    mest = models.IntegerField(null = True) 
    tags = models.CharField( blank = False,choices=tag, max_length=50,verbose_name='Тэг',null=True)
    zapis = models.ManyToManyField(AdvUser, related_name='Записаные',blank=True, verbose_name='Записаные', through='PostType', through_fields=('post','user'))

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = 'События'
        verbose_name = 'Событие'
        ordering = ['eventdate']

    def filename(self):
        return os.path.basename(self.file.name)

class PostType(models.Model):
    user = models.ForeignKey(AdvUser,on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE, null=True)
    zap_type = models.BooleanField(default=False, db_index=True,verbose_name='Групповая запись')
    colvo= models.IntegerField(null = True,verbose_name='Количество занятых мест')

    class Meta:
        verbose_name_plural = 'Записи мероприятий'
        verbose_name = 'Запись мероприяти'

class Event(models.Model):
    eventtime = models.TimeField(db_index=True,null=True,blank=False,verbose_name='Время')
    eventdate = models.DateField(db_index=True,null=True,blank=False,verbose_name='Дата')
    zan = models.BooleanField(default=False, db_index=True,verbose_name='Занято')
    zapisi = models.ManyToManyField(AdvUser, related_name='Записи',blank=True,verbose_name='Записаные')
    group = models.BooleanField(default=False, db_index=True,verbose_name='Групповая')

    def __str__(self):
        return f'{self.eventtime} {self.eventdate}'

    class Meta:
        verbose_name_plural = 'Время и дата выставки'
        verbose_name = 'Время и дата выставки'



class Vist(models.Model):
    name = models.CharField(null=True, blank=False,max_length=100,verbose_name='Название')
    content = models.TextField(null=True, blank=False,verbose_name='Контент')
    image = models.ImageField(upload_to='image/%Y/%m/%d/', blank=True, null=True,verbose_name='Изображение')
    file = models.FileField(upload_to='files/%Y/%m/%d/', blank=True, null=True,verbose_name='Приклепленные файлы')
    video = models.FileField(upload_to='video/%Y/%m/%d/', blank=True, null=True,verbose_name='Видео')
    audio = models.FileField(upload_to='audio/%Y/%m/%d/', blank=True, null=True,verbose_name='Аудио')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, null=True,verbose_name='Автор')
    pubdate = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')
    stoim = models.CharField(null = True, blank = False, max_length=10,verbose_name='Стоимость')
    event = models.ManyToManyField(Event,related_name='Даты',blank=True,verbose_name='Время и дата')
    final_date = models.DateField(db_index=True,null=True,blank=False,verbose_name='Конец выставки')
    start_date = models.DateField(db_index=True,null=True,blank=False,verbose_name='Начало выставки')

    class Meta:
        verbose_name_plural = 'Выставки'
        verbose_name = 'Выставка'
        ordering = ['pubdate']

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True ,null=True,verbose_name='Мероприятие')
    vist = models.ForeignKey(Vist, on_delete=models.CASCADE, blank=True , null=True,verbose_name='Выставка')
    content = models.TextField(null=True, blank=False,verbose_name='Контент')
    author = models.CharField(max_length=30,verbose_name='Автор')
    pubdate = models.DateTimeField(auto_now_add=True, db_index=True,verbose_name='Дата публикации')
    moderation = models.BooleanField(default=False,verbose_name='Модерация')

    class Meta:
        verbose_name_plural = 'Отзывы'
        verbose_name = 'Отзыв'
        ordering = ['-pubdate']


class Section(models.Model):
    name = models.CharField(max_length=30,verbose_name='Название')
    otobr = models.BooleanField(default=False, db_index=True,verbose_name='Отображение')

    class Meta:
        verbose_name_plural = 'Секции'
        verbose_name = 'Секция'

class Tvor(models.Model):
    name = models.CharField(max_length=30,verbose_name='Название')
    otobr = models.BooleanField(default=False, db_index=True,verbose_name='Отображение')

    class Meta:
        verbose_name_plural = 'Творческие направления'
        verbose_name = 'Творческое направление'

class Trud(models.Model):
    name = models.CharField(max_length=30,verbose_name='Название')
    otobr = models.BooleanField(default=False, db_index=True,verbose_name='Отображение')

    class Meta:
        verbose_name_plural = 'Трудовые направления'
        verbose_name = 'Трудовое направление'

class Volant(models.Model):
    name = models.CharField(max_length=30,verbose_name='Название')
    otobr = models.BooleanField(default=False, db_index=True,verbose_name='Отображение')

    class Meta:
        verbose_name_plural = 'Волонтерские направления'
        verbose_name = 'Волонтерское направление'

user_registrated = Signal(['instance'])


def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)

gsu/news/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post, AdvUser, user_registrated, Comment, Consult, Vist, Event
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError


class Index(forms.Form):
    Начало = forms.DateTimeField(widget=forms.SelectDateWidget)
    Конец = forms.DateTimeField(widget=forms.SelectDateWidget)

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        widgets = {'post': forms.HiddenInput, 'author': forms.HiddenInput,'moderation':forms.HiddenInput,'vist': forms.HiddenInput}


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = AdvUser
        fields = ('username', 'avatar', 'email', 'first_name', 'last_name','phone_num','faculty','group')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Password(repeat)', widget=forms.PasswordInput,
                                help_text='Repeat password')

    def clean_passwird1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Passwords do not match',
                                                   code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'avatar', 'email', 'password1', 'password2',
                  'first_name', 'last_name','phone_num','faculty','group')

class Subscribe(forms.Form):
    message = forms.CharField(widget=forms.Textarea)
    pass

class Subscribeg(forms.Form):
    message = forms.CharField(widget=forms.Textarea)
    colvo = forms.IntegerField(min_value=1)

class UnSubscribeg(forms.Form):
    message = forms.CharField(widget=forms.Textarea)
    colvo = forms.IntegerField(min_value=1)

class Subscribegv(forms.Form):
    message = forms.CharField(widget=forms.Textarea)

class NewConsult(ModelForm):
    eventdate = forms.DateTimeField(widget=forms.SelectDateWidget,label='Дата')
    class Meta:
        model = Consult
        fields = '__all__'
        widgets = {'zan': forms.HiddenInput}

class zapis_consult(forms.Form):
    pass

class PostForm(ModelForm):
    eventdate = forms.DateTimeField(widget=forms.SelectDateWidget,label='Дата')
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {'author': forms.HiddenInput, 'zapis':forms.HiddenInput,'mesta_now':forms.HiddenInput}

class TvorForm(forms.Form):
    Роль = forms.ChoiceField(choices=(("Артист", "Артист"), ("Организатор", "Организатор")))

class VistForm(ModelForm):
    class Meta:
        model = Vist
        fields = '__all__'
        widgets = {'author': forms.HiddenInput,'event': forms.HiddenInput}

gsu/news/templates/news/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Редактировать профиль{% endblock %}

{% block content %}
<div class="profile">
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form }}
		<button type="submit" class="btn btn-success">Сохранить</button>
	</form>
</div>
{% endblock %}

gsu/news/templates/news/cult.html
{% extends "layout/basic.html" %}
{% block title %}Культурно-досуговая деятельность{% endblock %}

{% block content %}
<div class="post">
	Записаться на направление<br>
	{% for naprav in tvors %}
		{{naprav.name}}<br>
		{% if user.is_authenticated %}
			<a href="{% url 'news:tvor' pk=naprav.pk %}" class="post_link">Записаться</a><br>
		{% endif %}
	{% endfor %}
	{% if user.id == 4 or user.id == 1  %}
		<a href="{% url 'news:add' %}"  class="post_link">Создать событие</a><br>
	{% endif %}
</div>
<div class="calendar">
	Выберите период времени
	<form method="post">
		{% csrf_token %}
		<div>{{ form }}</div>
		<button type="submit">Выбрать</button>
	</form>
</div>
{% if posts %}
	{% for post in posts %}
		{% if post.tags == 'cult' %}
			<div class="post">
				<div class="post-author">
					<div class="post-author-a">
			    		<div>
							{% if post.tags == 'cult' %}
								<a href="{% url 'news:cult' %}" class="post_link">{{ post.get_tags_display}}</a><br>
							{% endif %}
							Дата публикации: {{ post.pubdate|date:"d M Y H:i" }}
						</div>
					</div>
					{% if user.is_authenticated %}
						<div class="post-author-b">
							<a href="{% url 'news:detail' pk=post.pk %}" class="post_link">⋮</a>
						</div>
					{% endif %}
				</div>
				<div class="post-content">
					{{ post.name}}<br>{{ post.eventtime }} {{ post.eventdate }}<br>
					Количество свободных мест: {{ post.mesta_now }}<br>
					Цена: {{ post.stoim }}<br>
					{% if user.is_authenticated %}
						{% if post in your_zapisi %}
							Вы записаны<br>
						{% endif %}
					{% endif %}
					{% if post.image %}
						<a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="media"></a>
					{% endif %}
				</div>
			</div>
		{% endif %}
	{% endfor %}
{% endif %}
</div>
{% endblock %}

gsu/news/templates/news/detail.html
{% extends "layout/basic.html" %}

{% block content %}
	<div class="post">
		<div class="post-author">
			<div class="post-author-a">
				<div>
					Дата публикации: {{ post.pubdate|date:"d M Y H:i" }}
				</div>
			</div>
		</div>
		<div class="post-content">
			{{ post.name}}<br>
			{{ post.content}}<br>{{ post.eventtime }} {{ post.eventdate }}<br>
			Количество свободных мест: {{ post.mesta_now }}<br>
			Цена: {{ post.stoim }}<br>
			{% if a <  post.eventdate  %}
				{% if post.mesta == 0 %}
					Нет мест<br>
				{% else %}
					{% if post in your_zapisi %}
						{% if b == post.eventdate %}
							Нельзя отписаться<br>
						{% else %}
							{% for posttype in posttypes %}
								{% if posttype.post_id == post.id%}
									{% if posttype.zap_type == False %}
										<a href="{% url 'news:otpis' pk=post.pk %}" class="post_link">ОТПИСАТЬСЯ ЛИЧНО</a><br>
									{% else %}
										<a href="{% url 'news:otpisg' pk=post.pk %}" class="post_link">ОТПИСАТЬ ГРУППУ</a><br>
									{% endif %}
								{% endif %}	
							{% endfor %}
						{% endif %}
					{% else %}
						{% if post.mesta_now == 0 %}
							Нет мест<br>
						{% else %}
							<a href="{% url 'news:zapis' pk=post.pk %}" class="post_link">ЗАПИСАТЬСЯ ЛИЧНО</a><br>
							<a href="{% url 'news:zapisg' pk=post.pk  %}" class="post_link">ГРУППОВАЯ ЗАПИСЬ</a><br>
						{% endif %}
					{% endif %}
					{% if post in your_zapisi %}
						Вы записаны<br>
					{% endif %}
				{% endif %}
			{% else %}
				Мероприятие прошло<br>
			{% endif %}
			{% if post.image %}
				<a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="media"></a>
			{% endif %}
			{% if post.video %}
				<video src="{{ post.video.url }}" class="media" controls="controls"></video><br>
			{% endif %}
			{% if post.audio %}
				<audio src="{{ post.audio.url }}" controls="controls"></audio><br>
			{% endif %}
			{% if post.file %}
				<a href='{{ post.file.url }}' target="-blank" class="file">{{post.filename}}</a><br>
			{% endif %}
			{% if user.is_superuser == 1 %}
				<a href="{% url 'news:delete_post' pk=post.pk %}"  class="post_link">Delete</a>
			{% endif %}
		</div>
	{% if messageSent %}
		Отзыв опубликуется после модерации
	{% endif %}
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-success">Добавить отзыв</button>
		</form><br>
		{% if comments %}
			{% for comment in comments %}
			<div class="comment">
				{{ comment.author }} {{ comment.pubdate|date:"d M Y H:i" }}<br>
				{{ comment.content|urlize }}<br>
			</div>
			{% endfor %}
		{% endif %}
	</div>
{% endblock %}

gsu/news/templates/news/index.html
{% extends "layout/basic.html" %}

{% block content %}
<div class="calendar">
	Выберите период времени
	<form method="post">
		{% csrf_token %}
		<div>{{ form }}</div>
		<button type="submit">Выбрать</button>
	</form>
</div>
{% if posts %}
{% for post in posts %}
	<div class="post">
		<div class="post-author">
			<div class="post-author-a">
			    <div>
			    	{% if post.tags == 'cult' %}
					<a href="{% url 'news:cult' %}" class="post_link">{{post.get_tags_display}}</a><br>
					{% elif post.tags == 'sport' %}
					<a href="{% url 'news:sport' %}" class="post_link">{{post.get_tags_display}}</a><br>
					{% elif post.tags == 'mass' %}
					<a href="{% url 'news:mass' %}" class="post_link">{{post.get_tags_display}}</a><br>
					{% if post.vist == True %}
					Выставка <br>
					{% endif %}
					{% elif post.tags == 'trud' %}
					<a href="{% url 'news:trud' %}" class="post_link">{{post.get_tags_display}}</a><br>
					{% endif %}
					Дата публикации: {{post.pubdate|date:"d M Y H:i" }}
				</div>
			</div>
			{% if user.is_authenticated %}
				<div class="post-author-b">
					<a href="{% url 'news:detail' pk=post.pk %}" class="post_link">⋮</a>
				</div>
			{% endif %}
		</div>
		<div class="post-content">
			{{ post.name}}<br>  {{ post.eventtime }} {{ post.eventdate }}<br>
			{% if post.image %}
				<img src="{{ post.image.url }}" class="media"><br>
			{% endif %}
			Количество свободных мест: {{ post.mesta_now }}<br>
		</div>
	</div>
{% endfor %}
{% endif %}
{% endblock %}

gsu/news/templates/news/mass.html
{% extends "layout/basic.html" %}
{% block title %}Массовые мероприятия и выставки{% endblock %}

{% block content %}
{% if user.id == 6 or user.id == 1  %}
	<div class="post">
		<a href="{% url 'news:add' %}"  class="post_link">Создать событие</a><br>
		<a href="{% url 'news:add_v' %}"  class="post_link">Добавить выставку</a><br>
	</div>
{% endif %}
<div class="calendar">
	Выберите период времени
	<form method="post">
		{% csrf_token %}
		<div>{{ form }}</div>
		<button type="submit">Выбрать</button>
	</form>
</div>
{% if vists %}
	{% for vist in vists %}
		<div class="post">
			<div class="post-author">
				<div class="post-author-a">
			    	<div>
						Выставка <br>
						Дата публикации: {{ vist.pubdate|date:"d M Y H:i" }}<br>
						C {{ vist.start_date|date:"d M Y" }} ПО {{ vist.final_date|date:"d M Y" }}<br>
					</div>
				</div>
				{% if user.is_authenticated %}
					<div class="post-author-b">
						<a href="{% url 'news:detail_v' pk=vist.pk %}" class="post_link">⋮</a>
					</div>
				{% endif %}
			</div>
			<div class="post-content">
				{{ vist.name}}<br>
				Цена: {{ vist.stoim }}<br>
				{% if vist.image %}
					<a href="{{ vist.image.url }}"><img src="{{ vist.image.url }}" class="media"></a>
				{% endif %}
			</div>
		</div>
	{% endfor %}
{% endif %}
{% if posts %}
	{% for post in posts %}
		{% if post.tags == 'mass' %}
			<div class="post">
				<div class="post-author">
					<div class="post-author-a">
			    		<div>
							{% if post.tags == 'mass' %}
								<a href="{% url 'news:mass' %}" class="post_link">{{ post.get_tags_display}}</a><br>
								{% if post.vist == True %}
									Выставка <br>
								{% endif %}
							{% endif %}
							Дата публикации: {{ post.pubdate|date:"d M Y H:i" }}
						</div>
					</div>
					{% if user.is_authenticated %}
						<div class="post-author-b">
							<a href="{% url 'news:detail' pk=post.pk %}" class="link">⋮</a>
						</div>
					{% endif %}
				</div>
				<div class="post-content">
					{{ post.name}}<br> {{ post.eventtime }} {{ post.eventdate }}<br>
					Количество свободных мест: {{ post.mesta }}<br>
					Цена: {{ post.stoim }}<br>
					{% if user.is_authenticated %}
						{% if post in your_zapisi %}
							Вы записаны<br>
						{% endif %}
					{% endif %}
					{% if post.image %}
						<a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="media"></a>
					{% endif %}
				</div>
			</div>
		{% endif %}
	{% endfor %}
{% endif %}
{% endblock %}

gsu/news/templates/news/trud.html
{% extends "layout/basic.html" %}
{% block title %}Трудовая и волонтерская деятельность{% endblock %}

{% block content %}
	<div class="post">
		Записаться на трудовое направление<br>
		{% for trud in truds %}
			{{trud.name}}<br>
			{% if user.is_authenticated %}
				<a href="{% url 'news:trud_naprav' pk=trud.pk %}" class="post_link">Записаться</a><br>
			{% endif %}
		{% endfor %}
		Записаться на волонтерское направление<br>
		{% for volont in volonts %}
			{{volont.name}}<br>
			{% if user.is_authenticated %}
				<a href="{% url 'news:volon_naprav' pk=volont.pk %}" class="post_link">Записаться</a><br>
			{% endif %}
		{% endfor %}
		{% if user.id == 7 or user.id == 1  %}
			<a href="{% url 'news:add' %}"  class="post_link">Создать событие</a><br>
		{% endif %}
	</div>
<div class="calendar">
	Выберите период времени
	<form method="post">
		{% csrf_token %}
		<div>{{ form }}</div>
		<button type="submit">Выбрать</button>
	</form>
</div>
{% if posts %}
{% for post in posts %}
{% if post.tags == 'trud' %}
	<div class="post">
		<div class="post-author">
			<div class="post-author-a">
			    <div>
					{% if post.tags == 'trud' %}
					<a href="{% url 'news:trud' %}" class="post_link">{{ post.get_tags_display}}</a><br>
					{% endif %}
					Дата публикации: {{ post.pubdate|date:"d M Y H:i" }}
				</div>
			</div>
			{% if user.is_authenticated %}
				<div class="post-author-b">
					<a href="{% url 'news:detail' pk=post.pk %}" class="post_link">⋮</a>
				</div>
			{% endif %}
		</div>
		<div class="post-content">
			{{ post.name}}<br>{{ post.eventtime }} {{ post.eventdate }}<br>
			Количество свободных мест: {{ post.mesta }}<br>
			Цена: {{ post.stoim }}<br>
			{% if user.is_authenticated %}
				{% if post in your_zapisi %}
					Вы записаны<br>
				{% endif %}
			{% endif %}

			{% if post.image %}
				<a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="media"></a>
			{% endif %}
		</div>
	</div>
{% endif %}
{% endfor %}
{% endif %}
</div>
{% endblock %}